### ISSUE TITLE
Error: Cannot find module 'electron'

### ISSUE THREAD

**Issue by JoffreyN** [opendx/agent#1]
`Error: Cannot find module 'electron'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Program Files\Appium\resources\app\node_modules\electron-settings\lib\settings.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
`

**Comment by jiangyitao** [comment]
@JoffreyN 这是agent启动报的错吗，看起来像appium的配置不对？

**Comment by JoffreyN** [comment]
@jiangyitao 单独用appium是没问题的

**Comment by jiangyitao** [comment]
@JoffreyN 还是建议用npm install装appium吧，桌面版的我也不知道会搞出啥问题
