### ISSUE TITLE
华为手机，启动agent 报错；

### ISSUE THREAD

**Issue by supercating** [opendx/agent#6]
server
Exception in thread "Thread-4" java.lang.RuntimeException: [rgcitcgenfkfmreq]初始化失败
	at com.daxiang.core.mobile.MobileChangeHandler.mobileConnected(MobileChangeHandler.java:38)
	at com.daxiang.core.mobile.android.AndroidDeviceChangeListener.androidDeviceConnected(AndroidDeviceChangeListener.java:57)
	at com.daxiang.core.mobile.android.AndroidDeviceChangeListener.lambda$deviceConnected$0(AndroidDeviceChangeListener.java:36)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/wutianle/Library/Android/sdk/platform-tools/adb -P 5037 -s rgcitcgenfkfmreq shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 255'; Stderr: 'Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:1815)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1023)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1006)
	at com.android.providers.settings.SettingsProvider.delete(SettingsProvider.java:592)
	at android.content.ContentProvider$Transport.delete(ContentProvider.java:343)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:406)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:289)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:51)
	at android.os.Binder.shellCommand(Binder.java:629)
	at android.os.Binder.onTransact(Binder.java:527)
	at android.os.Binder.execTransact(Binder.java:726)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:1815)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1023)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1006)
	at com.android.providers.settings.SettingsProvider.delete(SettingsProvider.java:592)
	at android.content.ContentProvider$Transport.delete(ContentProvider.java:343)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:406)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:289)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:51)
	at android.os.Binder.shellCommand(Binder.java:629)
	at android.os.Binder.onTransact(Binder.java:527)
	at android.os.Binder.execTransact(Binder.java:726)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:1815)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1023)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1006)
	at com.android.providers.settings.SettingsProvider.delete(SettingsProvider.java:592)
	at android.content.ContentProvider$Transport.delete(ContentProvider.java:343)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:406)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:289)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:51)
	at android.os.Binder.shellCommand(Binder.java:629)
	at android.os.Binder.onTransact(Binder.java:527)
	at android.os.Binder.execTransact(Binder.java:726)'; Code: '255'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'wutianle', ip: 'fe80:0:0:0:1ce1:c33:ce74:5d34%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.6', java.version: '1.8.0_261'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/wutianle/Library/Android/sdk/platform-tools/adb -P 5037 -s rgcitcgenfkfmreq shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 255'; Stderr: 'Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:1815)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1023)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1006)
	at com.android.providers.settings.SettingsProvider.delete(SettingsProvider.java:592)
	at android.content.ContentProvider$Transport.delete(ContentProvider.java:343)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:406)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:289)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:51)
	at android.os.Binder.shellCommand(Binder.java:629)
	at android.os.Binder.onTransact(Binder.java:527)
	at android.os.Binder.execTransact(Binder.java:726)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:1815)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1023)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1006)
	at com.android.providers.settings.SettingsProvider.delete(SettingsProvider.java:592)
	at android.content.ContentProvider$Transport.delete(ContentProvider.java:343)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:406)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:289)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:51)
	at android.os.Binder.shellCommand(Binder.java:629)
	at android.os.Binder.onTransact(Binder.java:527)
	at android.os.Binder.execTransact(Binder.java:726)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:1815)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1023)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1006)
	at com.android.providers.settings.SettingsProvider.delete(SettingsProvider.java:592)
	at android.content.ContentProvider$Transport.delete(ContentProvider.java:343)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:406)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:289)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:51)
	at android.os.Binder.shellCommand(Binder.java:629)
	at android.os.Binder.onTransact(Binder.java:527)
	at android.os.Binder.execTransact(Binder.java:726)'; Code: '255'
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:381:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'wutianle', ip: 'fe80:0:0:0:1ce1:c33:ce74:5d34%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.6', java.version: '1.8.0_261'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:95)
	at com.daxiang.core.mobile.android.AndroidDevice.newDriver(AndroidDevice.java:73)
	at com.daxiang.core.Device.freshDriver(Device.java:119)
	at com.daxiang.core.mobile.android.AndroidDeviceChangeListener.initMobile(AndroidDeviceChangeListener.java:108)
	at com.daxiang.core.mobile.MobileChangeHandler.mobileConnected(MobileChangeHandler.java:34)
	... 3 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
	... 19 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/wutianle/Library/Android/sdk/platform-tools/adb -P 5037 -s rgcitcgenfkfmreq shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 255'; Stderr: 'Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:1815)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1023)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1006)
	at com.android.providers.settings.SettingsProvider.delete(SettingsProvider.java:592)
	at android.content.ContentProvider$Transport.delete(ContentProvider.java:343)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:406)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:289)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:51)
	at android.os.Binder.shellCommand(Binder.java:629)
	at android.os.Binder.onTransact(Binder.java:527)
	at android.os.Binder.execTransact(Binder.java:726)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:1815)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1023)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1006)
	at com.android.providers.settings.SettingsProvider.delete(SettingsProvider.java:592)
	at android.content.ContentProvider$Transport.delete(ContentProvider.java:343)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:406)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:289)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:51)
	at android.os.Binder.shellCommand(Binder.java:629)
	at android.os.Binder.onTransact(Binder.java:527)
	at android.os.Binder.execTransact(Binder.java:726)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:1815)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1023)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1006)
	at com.android.providers.settings.SettingsProvider.delete(SettingsProvider.java:592)
	at android.content.ContentProvider$Transport.delete(ContentProvider.java:343)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:406)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:289)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:51)
	at android.os.Binder.shellCommand(Binder.java:629)
	at android.os.Binder.onTransact(Binder.java:527)
	at android.os.Binder.execTransact(Binder.java:726)'; Code: '255'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'wutianle', ip: 'fe80:0:0:0:1ce1:c33:ce74:5d34%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.6', java.version: '1.8.0_261'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/wutianle/Library/Android/sdk/platform-tools/adb -P 5037 -s rgcitcgenfkfmreq shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 255'; Stderr: 'Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:1815)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1023)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1006)
	at com.android.providers.settings.SettingsProvider.delete(SettingsProvider.java:592)
	at android.content.ContentProvider$Transport.delete(ContentProvider.java:343)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:406)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:289)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:51)
	at android.os.Binder.shellCommand(Binder.java:629)
	at android.os.Binder.onTransact(Binder.java:527)
	at android.os.Binder.execTransact(Binder.java:726)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:1815)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1023)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1006)
	at com.android.providers.settings.SettingsProvider.delete(SettingsProvider.java:592)
	at android.content.ContentProvider$Transport.delete(ContentProvider.java:343)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:406)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:289)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:51)
	at android.os.Binder.shellCommand(Binder.java:629)
	at android.os.Binder.onTransact(Binder.java:527)
	at android.os.Binder.execTransact(Binder.java:726)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:1815)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1023)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1006)
	at com.android.providers.settings.SettingsProvider.delete(SettingsProvider.java:592)
	at android.content.ContentProvider$Transport.delete(ContentProvider.java:343)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:406)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:289)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:51)
	at android.os.Binder.shellCommand(Binder.java:629)
	at android.os.Binder.onTransact(Binder.java:527)
	at android.os.Binder.execTransact(Binder.java:726)'; Code: '255'
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:381:37)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	... 24 more

**Comment by jiangyitao** [comment]
手机设置问题
